apiVersion: v1
version: 6.2.3
appVersion: 6.2.3
name: podinfo
engine: gotpl
description: Podinfo Helm chart for Kubernetes
home: https://github.com/Summers1971/podinfo
maintainers:
- email: Summers1971@users.noreply.github.com
  name: Summers1971
sources:
- https://github.com/Summers1971/podinfo
kubeVersion: ">=1.19.0-0"
